version: '3'
services:
  edge-daemon:
    build:
      context: .
      dockerfile: Dockerfile-edge
    command: gladius-edge
    ports:
      - "5000:5000"
      - "8080:8080"
  control-daemon:
    build:
      context: .
      dockerfile: Dockerfile-control
    command: gladius-control
    ports:
      - "3000:3000"
